### ISSUE TITLE
No single person is authoritative over the RFC process

### ISSUE THREAD

**Issue by infinisil** [KFearsoff/nix-drama-explained#3]
> Cool. The RFC process was established since Feb 11, 2017. Eelco had been the authority in RFC process for 7 years.

From what I've seen in the steering committee as a [relatively new member](https://discourse.nixos.org/t/rfc-steering-committee-looking-for-new-members/21875/5?u=infinisil), there's really no authority over the process. The lead is rotated for each meeting, and there's also no extra authority when one is lead.

**Comment by KFearsoff** [comment]
My wording here was a little unclear. I didn't mean to imply that Eelco have held authority over all RFCs single-handedly; what I meant to say is that he had enjoyed a position of elevated authority (compared to someone who isn't part of the RFC Steering Committee) for years.

I rewrote this part to better reflect my thoughts. I've also added extremely important details on how him being in the RFC Steering Committee is problematic. See this commit for contents: https://github.com/KFearsoff/nix-drama-explained/commit/8be3766be313840b52bb315b44e34d64abb60cb3

Does this address the issue?

**Comment by infinisil** [comment]
Pretty much. I like the additional mention of RFC 49, though I don't quite agree with

> This clearly poses a conflict of interests: as a member of RFC Steering Committee, he is supposed to maintain unbiased perspective on the discussion at hand, but he is also an author of RFC and the major player in driving this discussion.

The steering committee mainly just decides over the shepherds of an RFC, that's where they could introduce bias. But that also only matters if you even have enough shepherds to even make a choice, in most cases it's barely enough to even reach the minimum number of 3. I haven't checked that particular RFC for this, but I don't think there was any bias regarding the steering committee there. Also it wouldn't matter anyways, because Eelco closed the RFC himself, the shepherds ultimately didn't make a decision on its acceptance.
